/*
FORCESNLPsolver : A fast customized optimization solver.

Copyright (C) 2013-2018 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCES PRO v1.6.121 on Friday, March 23, 2018 at 8:46:25 PM */

#include <stdio.h>

#ifndef __FORCESNLPsolver_H__
#define __FORCESNLPsolver_H__

/* DATA TYPE ------------------------------------------------------------*/
typedef double FORCESNLPsolver_float;

typedef double FORCESNLPsolverinterface_float;

#ifndef __SOLVER_STANDARD_TYPES__
#define __SOLVER_STANDARD_TYPES__

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif

#ifndef __SOLVER_STANDARD_TYPES__
#define __SOLVER_STANDARD_TYPES__

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif

/* SOLVER SETTINGS ------------------------------------------------------*/
/* print level */
#ifndef FORCESNLPsolver_SET_PRINTLEVEL
#define FORCESNLPsolver_SET_PRINTLEVEL    (2)
#endif

/* timing */
#ifndef FORCESNLPsolver_SET_TIMING
#define FORCESNLPsolver_SET_TIMING    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define FORCESNLPsolver_SET_MAXIT			(400)	

/* scaling factor of line search (FTB rule) */
#define FORCESNLPsolver_SET_FLS_SCALE		(FORCESNLPsolver_float)(0.99)      

/* maximum number of supported elements in the filter */
#define FORCESNLPsolver_MAX_FILTER_SIZE	(400) 

/* maximum number of supported elements in the filter */
#define FORCESNLPsolver_MAX_SOC_IT			(4) 

/* desired relative duality gap */
#define FORCESNLPsolver_SET_ACC_RDGAP		(FORCESNLPsolver_float)(0.0001)

/* desired maximum residual on equality constraints */
#define FORCESNLPsolver_SET_ACC_RESEQ		(FORCESNLPsolver_float)(1E-06)

/* desired maximum residual on inequality constraints */
#define FORCESNLPsolver_SET_ACC_RESINEQ	(FORCESNLPsolver_float)(1E-06)

/* desired maximum violation of complementarity */
#define FORCESNLPsolver_SET_ACC_KKTCOMPL	(FORCESNLPsolver_float)(1E-06)


/* RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define FORCESNLPsolver_OPTIMAL      (1)

/* maximum number of iterations has been reached */
#define FORCESNLPsolver_MAXITREACHED (0)

/* factorization error */
#define FORCESNLPsolver_FACTORIZATION_ERROR   (-5)

/* NaN encountered in function evaluations */
#define FORCESNLPsolver_BADFUNCEVAL  (-6)

/* no progress in method possible */
#define FORCESNLPsolver_NOPROGRESS   (-7)

/* licensing error - solver not valid on this machine */
#define FORCESNLPsolver_LICENSE_ERROR  (-100)



/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct FORCESNLPsolver_params
{
    /* vector of size 600 */
    FORCESNLPsolver_float x0[600];

    /* vector of size 4 */
    FORCESNLPsolver_float xinit[4];

    /* vector of size 2 */
    FORCESNLPsolver_float xfinal[2];

} FORCESNLPsolver_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct FORCESNLPsolver_output
{
    /* vector of size 6 */
    FORCESNLPsolver_float x001[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x002[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x003[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x004[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x005[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x006[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x007[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x008[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x009[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x010[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x011[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x012[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x013[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x014[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x015[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x016[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x017[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x018[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x019[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x020[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x021[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x022[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x023[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x024[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x025[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x026[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x027[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x028[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x029[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x030[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x031[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x032[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x033[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x034[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x035[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x036[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x037[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x038[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x039[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x040[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x041[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x042[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x043[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x044[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x045[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x046[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x047[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x048[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x049[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x050[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x051[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x052[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x053[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x054[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x055[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x056[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x057[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x058[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x059[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x060[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x061[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x062[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x063[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x064[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x065[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x066[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x067[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x068[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x069[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x070[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x071[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x072[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x073[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x074[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x075[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x076[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x077[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x078[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x079[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x080[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x081[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x082[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x083[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x084[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x085[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x086[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x087[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x088[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x089[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x090[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x091[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x092[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x093[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x094[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x095[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x096[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x097[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x098[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x099[6];

    /* vector of size 6 */
    FORCESNLPsolver_float x100[6];

} FORCESNLPsolver_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct FORCESNLPsolver_info
{
    /* iteration number */
    solver_int32_default it;

	/* number of iterations needed to optimality (branch-and-bound) */
	solver_int32_default it2opt;
	
    /* inf-norm of equality constraint residuals */
    FORCESNLPsolver_float res_eq;
	
    /* inf-norm of inequality constraint residuals */
    FORCESNLPsolver_float res_ineq;

	/* norm of stationarity condition */
    FORCESNLPsolver_float rsnorm;

	/* max of all complementarity violations */
    FORCESNLPsolver_float rcompnorm;

    /* primal objective */
    FORCESNLPsolver_float pobj;	
	
    /* dual objective */
    FORCESNLPsolver_float dobj;	

    /* duality gap := pobj - dobj */
    FORCESNLPsolver_float dgap;		
	
    /* relative duality gap := |dgap / pobj | */
    FORCESNLPsolver_float rdgap;		

    /* duality measure */
    FORCESNLPsolver_float mu;

	/* duality measure (after affine step) */
    FORCESNLPsolver_float mu_aff;
	
    /* centering parameter */
    FORCESNLPsolver_float sigma;
	
    /* number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;
    
    /* number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;
    
    /* step size (affine direction) */
    FORCESNLPsolver_float step_aff;
    
    /* step size (combined direction) */
    FORCESNLPsolver_float step_cc;    

	/* solvertime */
	FORCESNLPsolver_float solvetime;   

	/* time spent in function evaluations */
	FORCESNLPsolver_float fevalstime;  

} FORCESNLPsolver_info;








/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef void (*FORCESNLPsolver_extfunc)(FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, FORCESNLPsolver_float*, solver_int32_default);

extern solver_int32_default FORCESNLPsolver_solve(FORCESNLPsolver_params *params, FORCESNLPsolver_output *output, FORCESNLPsolver_info *info, FILE *fs, FORCESNLPsolver_extfunc FORCESNLPsolver_evalextfunctions);	


#ifdef __cplusplus
}
#endif

#endif