
#ifndef CASADI_SUNDIALS_COMMON_EXPORT_H
#define CASADI_SUNDIALS_COMMON_EXPORT_H

#ifdef CASADI_SUNDIALS_COMMON_STATIC_DEFINE
#  define CASADI_SUNDIALS_COMMON_EXPORT
#  define CASADI_SUNDIALS_COMMON_NO_EXPORT
#else
#  ifndef CASADI_SUNDIALS_COMMON_EXPORT
#    ifdef casadi_sundials_common_EXPORTS
        /* We are building this library */
#      define CASADI_SUNDIALS_COMMON_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_SUNDIALS_COMMON_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_SUNDIALS_COMMON_NO_EXPORT
#    define CASADI_SUNDIALS_COMMON_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_SUNDIALS_COMMON_DEPRECATED
#  define CASADI_SUNDIALS_COMMON_DEPRECATED 
#endif

#ifndef CASADI_SUNDIALS_COMMON_DEPRECATED_EXPORT
#  define CASADI_SUNDIALS_COMMON_DEPRECATED_EXPORT CASADI_SUNDIALS_COMMON_EXPORT CASADI_SUNDIALS_COMMON_DEPRECATED
#endif

#ifndef CASADI_SUNDIALS_COMMON_DEPRECATED_NO_EXPORT
#  define CASADI_SUNDIALS_COMMON_DEPRECATED_NO_EXPORT CASADI_SUNDIALS_COMMON_NO_EXPORT CASADI_SUNDIALS_COMMON_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_SUNDIALS_COMMON_NO_DEPRECATED
#endif

#endif
