
#ifndef CASADI_DPLESOLVER_CONDENSING_EXPORT_H
#define CASADI_DPLESOLVER_CONDENSING_EXPORT_H

#ifdef CASADI_DPLESOLVER_CONDENSING_STATIC_DEFINE
#  define CASADI_DPLESOLVER_CONDENSING_EXPORT
#  define CASADI_DPLESOLVER_CONDENSING_NO_EXPORT
#else
#  ifndef CASADI_DPLESOLVER_CONDENSING_EXPORT
#    ifdef casadi_dplesolver_condensing_EXPORTS
        /* We are building this library */
#      define CASADI_DPLESOLVER_CONDENSING_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_DPLESOLVER_CONDENSING_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_DPLESOLVER_CONDENSING_NO_EXPORT
#    define CASADI_DPLESOLVER_CONDENSING_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_DPLESOLVER_CONDENSING_DEPRECATED
#  define CASADI_DPLESOLVER_CONDENSING_DEPRECATED 
#endif

#ifndef CASADI_DPLESOLVER_CONDENSING_DEPRECATED_EXPORT
#  define CASADI_DPLESOLVER_CONDENSING_DEPRECATED_EXPORT CASADI_DPLESOLVER_CONDENSING_EXPORT CASADI_DPLESOLVER_CONDENSING_DEPRECATED
#endif

#ifndef CASADI_DPLESOLVER_CONDENSING_DEPRECATED_NO_EXPORT
#  define CASADI_DPLESOLVER_CONDENSING_DEPRECATED_NO_EXPORT CASADI_DPLESOLVER_CONDENSING_NO_EXPORT CASADI_DPLESOLVER_CONDENSING_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_DPLESOLVER_CONDENSING_NO_DEPRECATED
#endif

#endif
