
#ifndef CASADI_NLPSOLVER_SQPMETHOD_EXPORT_H
#define CASADI_NLPSOLVER_SQPMETHOD_EXPORT_H

#ifdef CASADI_NLPSOLVER_SQPMETHOD_STATIC_DEFINE
#  define CASADI_NLPSOLVER_SQPMETHOD_EXPORT
#  define CASADI_NLPSOLVER_SQPMETHOD_NO_EXPORT
#else
#  ifndef CASADI_NLPSOLVER_SQPMETHOD_EXPORT
#    ifdef casadi_nlpsolver_sqpmethod_EXPORTS
        /* We are building this library */
#      define CASADI_NLPSOLVER_SQPMETHOD_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_NLPSOLVER_SQPMETHOD_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_NLPSOLVER_SQPMETHOD_NO_EXPORT
#    define CASADI_NLPSOLVER_SQPMETHOD_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_NLPSOLVER_SQPMETHOD_DEPRECATED
#  define CASADI_NLPSOLVER_SQPMETHOD_DEPRECATED 
#endif

#ifndef CASADI_NLPSOLVER_SQPMETHOD_DEPRECATED_EXPORT
#  define CASADI_NLPSOLVER_SQPMETHOD_DEPRECATED_EXPORT CASADI_NLPSOLVER_SQPMETHOD_EXPORT CASADI_NLPSOLVER_SQPMETHOD_DEPRECATED
#endif

#ifndef CASADI_NLPSOLVER_SQPMETHOD_DEPRECATED_NO_EXPORT
#  define CASADI_NLPSOLVER_SQPMETHOD_DEPRECATED_NO_EXPORT CASADI_NLPSOLVER_SQPMETHOD_NO_EXPORT CASADI_NLPSOLVER_SQPMETHOD_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_NLPSOLVER_SQPMETHOD_NO_DEPRECATED
#endif

#endif
