
#ifndef CASADI_DLESOLVER_FIXED_SMITH_EXPORT_H
#define CASADI_DLESOLVER_FIXED_SMITH_EXPORT_H

#ifdef CASADI_DLESOLVER_FIXED_SMITH_STATIC_DEFINE
#  define CASADI_DLESOLVER_FIXED_SMITH_EXPORT
#  define CASADI_DLESOLVER_FIXED_SMITH_NO_EXPORT
#else
#  ifndef CASADI_DLESOLVER_FIXED_SMITH_EXPORT
#    ifdef casadi_dlesolver_fixed_smith_EXPORTS
        /* We are building this library */
#      define CASADI_DLESOLVER_FIXED_SMITH_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_DLESOLVER_FIXED_SMITH_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_DLESOLVER_FIXED_SMITH_NO_EXPORT
#    define CASADI_DLESOLVER_FIXED_SMITH_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_DLESOLVER_FIXED_SMITH_DEPRECATED
#  define CASADI_DLESOLVER_FIXED_SMITH_DEPRECATED 
#endif

#ifndef CASADI_DLESOLVER_FIXED_SMITH_DEPRECATED_EXPORT
#  define CASADI_DLESOLVER_FIXED_SMITH_DEPRECATED_EXPORT CASADI_DLESOLVER_FIXED_SMITH_EXPORT CASADI_DLESOLVER_FIXED_SMITH_DEPRECATED
#endif

#ifndef CASADI_DLESOLVER_FIXED_SMITH_DEPRECATED_NO_EXPORT
#  define CASADI_DLESOLVER_FIXED_SMITH_DEPRECATED_NO_EXPORT CASADI_DLESOLVER_FIXED_SMITH_NO_EXPORT CASADI_DLESOLVER_FIXED_SMITH_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_DLESOLVER_FIXED_SMITH_NO_DEPRECATED
#endif

#endif
