
#ifndef CASADI_LRDLESOLVER_DLE_EXPORT_H
#define CASADI_LRDLESOLVER_DLE_EXPORT_H

#ifdef CASADI_LRDLESOLVER_DLE_STATIC_DEFINE
#  define CASADI_LRDLESOLVER_DLE_EXPORT
#  define CASADI_LRDLESOLVER_DLE_NO_EXPORT
#else
#  ifndef CASADI_LRDLESOLVER_DLE_EXPORT
#    ifdef casadi_lrdlesolver_dle_EXPORTS
        /* We are building this library */
#      define CASADI_LRDLESOLVER_DLE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_LRDLESOLVER_DLE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_LRDLESOLVER_DLE_NO_EXPORT
#    define CASADI_LRDLESOLVER_DLE_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_LRDLESOLVER_DLE_DEPRECATED
#  define CASADI_LRDLESOLVER_DLE_DEPRECATED 
#endif

#ifndef CASADI_LRDLESOLVER_DLE_DEPRECATED_EXPORT
#  define CASADI_LRDLESOLVER_DLE_DEPRECATED_EXPORT CASADI_LRDLESOLVER_DLE_EXPORT CASADI_LRDLESOLVER_DLE_DEPRECATED
#endif

#ifndef CASADI_LRDLESOLVER_DLE_DEPRECATED_NO_EXPORT
#  define CASADI_LRDLESOLVER_DLE_DEPRECATED_NO_EXPORT CASADI_LRDLESOLVER_DLE_NO_EXPORT CASADI_LRDLESOLVER_DLE_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_LRDLESOLVER_DLE_NO_DEPRECATED
#endif

#endif
