
#ifndef CASADI_STABILIZEDQPSOLVER_QP_EXPORT_H
#define CASADI_STABILIZEDQPSOLVER_QP_EXPORT_H

#ifdef CASADI_STABILIZEDQPSOLVER_QP_STATIC_DEFINE
#  define CASADI_STABILIZEDQPSOLVER_QP_EXPORT
#  define CASADI_STABILIZEDQPSOLVER_QP_NO_EXPORT
#else
#  ifndef CASADI_STABILIZEDQPSOLVER_QP_EXPORT
#    ifdef casadi_stabilizedqpsolver_qp_EXPORTS
        /* We are building this library */
#      define CASADI_STABILIZEDQPSOLVER_QP_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_STABILIZEDQPSOLVER_QP_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_STABILIZEDQPSOLVER_QP_NO_EXPORT
#    define CASADI_STABILIZEDQPSOLVER_QP_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_STABILIZEDQPSOLVER_QP_DEPRECATED
#  define CASADI_STABILIZEDQPSOLVER_QP_DEPRECATED 
#endif

#ifndef CASADI_STABILIZEDQPSOLVER_QP_DEPRECATED_EXPORT
#  define CASADI_STABILIZEDQPSOLVER_QP_DEPRECATED_EXPORT CASADI_STABILIZEDQPSOLVER_QP_EXPORT CASADI_STABILIZEDQPSOLVER_QP_DEPRECATED
#endif

#ifndef CASADI_STABILIZEDQPSOLVER_QP_DEPRECATED_NO_EXPORT
#  define CASADI_STABILIZEDQPSOLVER_QP_DEPRECATED_NO_EXPORT CASADI_STABILIZEDQPSOLVER_QP_NO_EXPORT CASADI_STABILIZEDQPSOLVER_QP_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_STABILIZEDQPSOLVER_QP_NO_DEPRECATED
#endif

#endif
