
#ifndef CASADI_LRDPLESOLVER_LIFTING_EXPORT_H
#define CASADI_LRDPLESOLVER_LIFTING_EXPORT_H

#ifdef CASADI_LRDPLESOLVER_LIFTING_STATIC_DEFINE
#  define CASADI_LRDPLESOLVER_LIFTING_EXPORT
#  define CASADI_LRDPLESOLVER_LIFTING_NO_EXPORT
#else
#  ifndef CASADI_LRDPLESOLVER_LIFTING_EXPORT
#    ifdef casadi_lrdplesolver_lifting_EXPORTS
        /* We are building this library */
#      define CASADI_LRDPLESOLVER_LIFTING_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_LRDPLESOLVER_LIFTING_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_LRDPLESOLVER_LIFTING_NO_EXPORT
#    define CASADI_LRDPLESOLVER_LIFTING_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_LRDPLESOLVER_LIFTING_DEPRECATED
#  define CASADI_LRDPLESOLVER_LIFTING_DEPRECATED 
#endif

#ifndef CASADI_LRDPLESOLVER_LIFTING_DEPRECATED_EXPORT
#  define CASADI_LRDPLESOLVER_LIFTING_DEPRECATED_EXPORT CASADI_LRDPLESOLVER_LIFTING_EXPORT CASADI_LRDPLESOLVER_LIFTING_DEPRECATED
#endif

#ifndef CASADI_LRDPLESOLVER_LIFTING_DEPRECATED_NO_EXPORT
#  define CASADI_LRDPLESOLVER_LIFTING_DEPRECATED_NO_EXPORT CASADI_LRDPLESOLVER_LIFTING_NO_EXPORT CASADI_LRDPLESOLVER_LIFTING_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_LRDPLESOLVER_LIFTING_NO_DEPRECATED
#endif

#endif
