
#ifndef CASADI_INTEGRATORS_EXPORT_H
#define CASADI_INTEGRATORS_EXPORT_H

#ifdef CASADI_INTEGRATORS_STATIC_DEFINE
#  define CASADI_INTEGRATORS_EXPORT
#  define CASADI_INTEGRATORS_NO_EXPORT
#else
#  ifndef CASADI_INTEGRATORS_EXPORT
#    ifdef casadi_integrators_EXPORTS
        /* We are building this library */
#      define CASADI_INTEGRATORS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_INTEGRATORS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_INTEGRATORS_NO_EXPORT
#    define CASADI_INTEGRATORS_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_INTEGRATORS_DEPRECATED
#  define CASADI_INTEGRATORS_DEPRECATED 
#endif

#ifndef CASADI_INTEGRATORS_DEPRECATED_EXPORT
#  define CASADI_INTEGRATORS_DEPRECATED_EXPORT CASADI_INTEGRATORS_EXPORT CASADI_INTEGRATORS_DEPRECATED
#endif

#ifndef CASADI_INTEGRATORS_DEPRECATED_NO_EXPORT
#  define CASADI_INTEGRATORS_DEPRECATED_NO_EXPORT CASADI_INTEGRATORS_NO_EXPORT CASADI_INTEGRATORS_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_INTEGRATORS_NO_DEPRECATED
#endif

#endif
