
#ifndef CASADI_NLPSOLVER_IPOPT_EXPORT_H
#define CASADI_NLPSOLVER_IPOPT_EXPORT_H

#ifdef CASADI_NLPSOLVER_IPOPT_STATIC_DEFINE
#  define CASADI_NLPSOLVER_IPOPT_EXPORT
#  define CASADI_NLPSOLVER_IPOPT_NO_EXPORT
#else
#  ifndef CASADI_NLPSOLVER_IPOPT_EXPORT
#    ifdef casadi_nlpsolver_ipopt_EXPORTS
        /* We are building this library */
#      define CASADI_NLPSOLVER_IPOPT_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_NLPSOLVER_IPOPT_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_NLPSOLVER_IPOPT_NO_EXPORT
#    define CASADI_NLPSOLVER_IPOPT_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_NLPSOLVER_IPOPT_DEPRECATED
#  define CASADI_NLPSOLVER_IPOPT_DEPRECATED 
#endif

#ifndef CASADI_NLPSOLVER_IPOPT_DEPRECATED_EXPORT
#  define CASADI_NLPSOLVER_IPOPT_DEPRECATED_EXPORT CASADI_NLPSOLVER_IPOPT_EXPORT CASADI_NLPSOLVER_IPOPT_DEPRECATED
#endif

#ifndef CASADI_NLPSOLVER_IPOPT_DEPRECATED_NO_EXPORT
#  define CASADI_NLPSOLVER_IPOPT_DEPRECATED_NO_EXPORT CASADI_NLPSOLVER_IPOPT_NO_EXPORT CASADI_NLPSOLVER_IPOPT_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_NLPSOLVER_IPOPT_NO_DEPRECATED
#endif

#endif
