/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) FORCESNLPsolver_model_45_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver/include/FORCESNLPsolver.h"

#define PRINTF printf
FORCESNLPsolver_float CASADI_PREFIX(sq)(FORCESNLPsolver_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_float CASADI_PREFIX(sign)(FORCESNLPsolver_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {0, 1, 0, 0};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 6, 0, 1, 2, 2, 3, 3, 3, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {2, 1, 0, 2, 0, 1};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {2, 6, 0, 0, 0, 2, 4, 4, 4, 0, 1, 0, 1};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
solver_int32_default FORCESNLPsolver_model_45(const FORCESNLPsolver_float **arg, FORCESNLPsolver_float **res) 
{
    FORCESNLPsolver_float a0,a1,a2,a3,a4,a5,a6,a7;
    
    a0=-100.;
    a1=arg[0] ? arg[0][3] : 0;
    a2=(a0*a1);
    a3=arg[0] ? arg[0][0] : 0;
    a4=sq(a3);
    a5=1.0000000000000001e-001;
    a4=(a5*a4);
    a2=(a2+a4);
    a4=arg[0] ? arg[0][1] : 0;
    a6=sq(a4);
    a7=1.0000000000000000e-002;
    a6=(a7*a6);
    a2=(a2+a6);
    if (res[0]!=0) res[0][0]=a2;
    a3=(a3+a3);
    a5=(a5*a3);
    if (res[1]!=0) res[1][0]=a5;
    a4=(a4+a4);
    a7=(a7*a4);
    if (res[1]!=0) res[1][1]=a7;
    if (res[1]!=0) res[1][2]=a0;
    a0=arg[0] ? arg[0][2] : 0;
    a7=sq(a0);
    a4=sq(a1);
    a7=(a7+a4);
    if (res[2]!=0) res[2][0]=a7;
    a7=2.;
    a7=(a0+a7);
    a4=sq(a7);
    a5=2.5000000000000000e+000;
    a5=(a1-a5);
    a3=sq(a5);
    a4=(a4+a3);
    if (res[2]!=0) res[2][1]=a4;
    a0=(a0+a0);
    if (res[3]!=0) res[3][0]=a0;
    a7=(a7+a7);
    if (res[3]!=0) res[3][1]=a7;
    a1=(a1+a1);
    if (res[3]!=0) res[3][2]=a1;
    a5=(a5+a5);
    if (res[3]!=0) res[3][3]=a5;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_45_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 4;
    *sz_arg = 2;
    *sz_res = 4;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_45_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 4:
        s = s4;
        break;
      case 5:
        s = s5;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default FORCESNLPsolver_model_45_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 8;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
