/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) FORCESNLPsolver_model_1_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver/include/FORCESNLPsolver.h"

#define PRINTF printf
FORCESNLPsolver_float CASADI_PREFIX(sq)(FORCESNLPsolver_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_float CASADI_PREFIX(sign)(FORCESNLPsolver_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {0, 1, 0, 0};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 6, 0, 1, 2, 2, 3, 3, 3, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {2, 1, 0, 2, 0, 1};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {2, 6, 0, 0, 0, 2, 4, 4, 4, 0, 1, 0, 1};
#define s5 CASADI_PREFIX(s5)
static const solver_int32_default CASADI_PREFIX(s6)[] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s6 CASADI_PREFIX(s6)
static const solver_int32_default CASADI_PREFIX(s7)[] = {4, 6, 0, 4, 7, 8, 9, 13, 16, 0, 1, 2, 3, 0, 1, 3, 0, 1, 0, 1, 2, 3, 0, 1, 3};
#define s7 CASADI_PREFIX(s7)
/* evaluate_stages */
solver_int32_default FORCESNLPsolver_model_1(const FORCESNLPsolver_float **arg, FORCESNLPsolver_float **res) 
{
    FORCESNLPsolver_float a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32;
    
    a0=-200.;
    a1=arg[0] ? arg[0][3] : 0;
    a2=(a0*a1);
    a3=arg[0] ? arg[0][0] : 0;
    a4=sq(a3);
    a5=1.0000000000000000e-003;
    a4=(a5*a4);
    a2=(a2+a4);
    a4=arg[0] ? arg[0][1] : 0;
    a6=sq(a4);
    a7=1.0000000000000000e-004;
    a6=(a7*a6);
    a2=(a2+a6);
    if (res[0]!=0) res[0][0]=a2;
    a2=(a3+a3);
    a5=(a5*a2);
    if (res[1]!=0) res[1][0]=a5;
    a5=(a4+a4);
    a7=(a7*a5);
    if (res[1]!=0) res[1][1]=a7;
    if (res[1]!=0) res[1][2]=a0;
    a0=arg[0] ? arg[0][2] : 0;
    a7=sq(a0);
    a5=sq(a1);
    a7=(a7+a5);
    if (res[2]!=0) res[2][0]=a7;
    a7=2.;
    a5=(a0+a7);
    a2=sq(a5);
    a6=2.5000000000000000e+000;
    a6=(a1-a6);
    a8=sq(a6);
    a2=(a2+a8);
    if (res[2]!=0) res[2][1]=a2;
    a2=(a0+a0);
    if (res[3]!=0) res[3][0]=a2;
    a5=(a5+a5);
    if (res[3]!=0) res[3][1]=a5;
    a5=(a1+a1);
    if (res[3]!=0) res[3][2]=a5;
    a6=(a6+a6);
    if (res[3]!=0) res[3][3]=a6;
    a6=arg[0] ? arg[0][5] : 0;
    a5=cos(a6);
    a2=arg[0] ? arg[0][4] : 0;
    a8=(a2*a5);
    a9=9.0000000000000002e-001;
    a10=(a3/a9);
    a11=5.0000000000000003e-002;
    a12=(a11*a10);
    a12=(a2+a12);
    a13=(a4*a2);
    a14=1.2000000000000000e-001;
    a13=(a13/a14);
    a15=(a11*a13);
    a15=(a6+a15);
    a16=cos(a15);
    a17=(a12*a16);
    a17=(a7*a17);
    a8=(a8+a17);
    a17=(a3/a9);
    a18=(a11*a17);
    a18=(a2+a18);
    a19=(a4*a12);
    a19=(a19/a14);
    a20=(a11*a19);
    a20=(a6+a20);
    a21=cos(a20);
    a22=(a18*a21);
    a22=(a7*a22);
    a8=(a8+a22);
    a22=(a3/a9);
    a23=1.0000000000000001e-001;
    a24=(a23*a22);
    a24=(a2+a24);
    a25=(a4*a18);
    a25=(a25/a14);
    a26=(a23*a25);
    a26=(a6+a26);
    a27=cos(a26);
    a28=(a24*a27);
    a8=(a8+a28);
    a28=1.6666666666666666e-002;
    a8=(a28*a8);
    a0=(a0+a8);
    if (res[4]!=0) res[4][0]=a0;
    a0=sin(a6);
    a8=(a2*a0);
    a29=sin(a15);
    a30=(a12*a29);
    a30=(a7*a30);
    a8=(a8+a30);
    a30=sin(a20);
    a31=(a18*a30);
    a31=(a7*a31);
    a8=(a8+a31);
    a31=sin(a26);
    a32=(a24*a31);
    a8=(a8+a32);
    a8=(a28*a8);
    a1=(a1+a8);
    if (res[4]!=0) res[4][1]=a1;
    a17=(a7*a17);
    a10=(a10+a17);
    a22=(a7*a22);
    a10=(a10+a22);
    a3=(a3/a9);
    a10=(a10+a3);
    a10=(a28*a10);
    a10=(a2+a10);
    if (res[4]!=0) res[4][2]=a10;
    a19=(a7*a19);
    a13=(a13+a19);
    a25=(a7*a25);
    a13=(a13+a25);
    a25=(a4*a24);
    a25=(a25/a14);
    a13=(a13+a25);
    a13=(a28*a13);
    a13=(a6+a13);
    if (res[4]!=0) res[4][3]=a13;
    a13=5.5555555555555559e-002;
    a25=(a13*a16);
    a25=(a7*a25);
    a14=(a13*a21);
    a19=(a13*a4);
    a10=8.3333333333333339e+000;
    a19=(a10*a19);
    a3=(a11*a19);
    a9=sin(a20);
    a22=(a9*a3);
    a22=(a18*a22);
    a14=(a14-a22);
    a14=(a7*a14);
    a25=(a25+a14);
    a14=1.1111111111111112e-001;
    a22=(a14*a27);
    a17=(a13*a4);
    a17=(a10*a17);
    a1=(a23*a17);
    a8=sin(a26);
    a32=(a8*a1);
    a32=(a24*a32);
    a22=(a22-a32);
    a25=(a25+a22);
    a25=(a28*a25);
    if (res[5]!=0) res[5][0]=a25;
    a25=(a13*a29);
    a25=(a7*a25);
    a13=(a13*a30);
    a20=cos(a20);
    a3=(a20*a3);
    a3=(a18*a3);
    a13=(a13+a3);
    a13=(a7*a13);
    a25=(a25+a13);
    a13=(a14*a31);
    a26=cos(a26);
    a1=(a26*a1);
    a1=(a24*a1);
    a13=(a13+a1);
    a25=(a25+a13);
    a25=(a28*a25);
    if (res[5]!=0) res[5][1]=a25;
    a25=1.1111111111111110e-001;
    if (res[5]!=0) res[5][2]=a25;
    a19=(a7*a19);
    a17=(a7*a17);
    a19=(a19+a17);
    a14=(a14*a4);
    a14=(a10*a14);
    a19=(a19+a14);
    a19=(a28*a19);
    if (res[5]!=0) res[5][3]=a19;
    a19=(a10*a2);
    a14=(a11*a19);
    a17=sin(a15);
    a25=(a17*a14);
    a25=(a12*a25);
    a25=(a7*a25);
    a13=(a10*a12);
    a1=(a11*a13);
    a3=(a9*a1);
    a3=(a18*a3);
    a3=(a7*a3);
    a25=(a25+a3);
    a3=(a10*a18);
    a22=(a23*a3);
    a32=(a8*a22);
    a32=(a24*a32);
    a25=(a25+a32);
    a25=(a28*a25);
    a25=(-a25);
    if (res[5]!=0) res[5][4]=a25;
    a15=cos(a15);
    a14=(a15*a14);
    a14=(a12*a14);
    a14=(a7*a14);
    a1=(a20*a1);
    a1=(a18*a1);
    a1=(a7*a1);
    a14=(a14+a1);
    a22=(a26*a22);
    a22=(a24*a22);
    a14=(a14+a22);
    a14=(a28*a14);
    if (res[5]!=0) res[5][5]=a14;
    a13=(a7*a13);
    a19=(a19+a13);
    a3=(a7*a3);
    a19=(a19+a3);
    a3=(a10*a24);
    a19=(a19+a3);
    a19=(a28*a19);
    if (res[5]!=0) res[5][6]=a19;
    a19=1.;
    if (res[5]!=0) res[5][7]=a19;
    if (res[5]!=0) res[5][8]=a19;
    a3=(a10*a4);
    a13=(a11*a3);
    a14=(a17*a13);
    a14=(a12*a14);
    a16=(a16-a14);
    a16=(a7*a16);
    a5=(a5+a16);
    a16=(a10*a4);
    a11=(a11*a16);
    a14=(a9*a11);
    a14=(a18*a14);
    a21=(a21-a14);
    a21=(a7*a21);
    a5=(a5+a21);
    a21=(a10*a4);
    a23=(a23*a21);
    a14=(a8*a23);
    a14=(a24*a14);
    a27=(a27-a14);
    a5=(a5+a27);
    a5=(a28*a5);
    if (res[5]!=0) res[5][9]=a5;
    a13=(a15*a13);
    a13=(a12*a13);
    a29=(a29+a13);
    a29=(a7*a29);
    a0=(a0+a29);
    a11=(a20*a11);
    a11=(a18*a11);
    a30=(a30+a11);
    a30=(a7*a30);
    a0=(a0+a30);
    a23=(a26*a23);
    a23=(a24*a23);
    a31=(a31+a23);
    a0=(a0+a31);
    a0=(a28*a0);
    if (res[5]!=0) res[5][10]=a0;
    if (res[5]!=0) res[5][11]=a19;
    a16=(a7*a16);
    a3=(a3+a16);
    a21=(a7*a21);
    a3=(a3+a21);
    a10=(a10*a4);
    a3=(a3+a10);
    a3=(a28*a3);
    if (res[5]!=0) res[5][12]=a3;
    a3=sin(a6);
    a3=(a2*a3);
    a17=(a12*a17);
    a17=(a7*a17);
    a3=(a3+a17);
    a9=(a18*a9);
    a9=(a7*a9);
    a3=(a3+a9);
    a8=(a24*a8);
    a3=(a3+a8);
    a3=(a28*a3);
    a3=(-a3);
    if (res[5]!=0) res[5][13]=a3;
    a6=cos(a6);
    a2=(a2*a6);
    a12=(a12*a15);
    a12=(a7*a12);
    a2=(a2+a12);
    a18=(a18*a20);
    a7=(a7*a18);
    a2=(a2+a7);
    a24=(a24*a26);
    a2=(a2+a24);
    a28=(a28*a2);
    if (res[5]!=0) res[5][14]=a28;
    if (res[5]!=0) res[5][15]=a19;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 6;
    *sz_arg = 2;
    *sz_res = 6;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 4:
        s = s4;
        break;
      case 5:
        s = s5;
        break;
      case 6:
        s = s6;
        break;
      case 7:
        s = s7;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 33;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
