
#ifndef CASADI_LINEARSOLVER_CSPARSECHOLESKY_EXPORT_H
#define CASADI_LINEARSOLVER_CSPARSECHOLESKY_EXPORT_H

#ifdef CASADI_LINEARSOLVER_CSPARSECHOLESKY_STATIC_DEFINE
#  define CASADI_LINEARSOLVER_CSPARSECHOLESKY_EXPORT
#  define CASADI_LINEARSOLVER_CSPARSECHOLESKY_NO_EXPORT
#else
#  ifndef CASADI_LINEARSOLVER_CSPARSECHOLESKY_EXPORT
#    ifdef casadi_linearsolver_csparsecholesky_EXPORTS
        /* We are building this library */
#      define CASADI_LINEARSOLVER_CSPARSECHOLESKY_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define CASADI_LINEARSOLVER_CSPARSECHOLESKY_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef CASADI_LINEARSOLVER_CSPARSECHOLESKY_NO_EXPORT
#    define CASADI_LINEARSOLVER_CSPARSECHOLESKY_NO_EXPORT 
#  endif
#endif

#ifndef CASADI_LINEARSOLVER_CSPARSECHOLESKY_DEPRECATED
#  define CASADI_LINEARSOLVER_CSPARSECHOLESKY_DEPRECATED 
#endif

#ifndef CASADI_LINEARSOLVER_CSPARSECHOLESKY_DEPRECATED_EXPORT
#  define CASADI_LINEARSOLVER_CSPARSECHOLESKY_DEPRECATED_EXPORT CASADI_LINEARSOLVER_CSPARSECHOLESKY_EXPORT CASADI_LINEARSOLVER_CSPARSECHOLESKY_DEPRECATED
#endif

#ifndef CASADI_LINEARSOLVER_CSPARSECHOLESKY_DEPRECATED_NO_EXPORT
#  define CASADI_LINEARSOLVER_CSPARSECHOLESKY_DEPRECATED_NO_EXPORT CASADI_LINEARSOLVER_CSPARSECHOLESKY_NO_EXPORT CASADI_LINEARSOLVER_CSPARSECHOLESKY_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CASADI_LINEARSOLVER_CSPARSECHOLESKY_NO_DEPRECATED
#endif

#endif
